In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_rows', None)

In [2]:
df = pd.read_csv('drive/MyDrive/violencia_2009_2021.csv')

<ipython-input-2-11b5eddc39a3>:1: DtypeWarning: Columns (14,16,20,42,48,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('drive/MyDrive/violencia_2009_2021.csv')


In [3]:
df.shape

(1700365, 100)

# Tratamentos a realizar
- Transformar nulos em nulos
- Transformar numéricos em numéricos
- Alterar os resultados das colunas para os do dicionário

In [4]:
col_conjunto = ['DEF_TRANS', 'OUT_VEZES', 'LES_AUTOP', 'VIOL_FISIC', 'VIOL_PSICO', 'VIOL_TORT', 'VIOL_SEXU',
                'VIOL_TRAF', 'VIOL_FINAN', 'VIOL_LEGAL', 'VIOL_NEGLI', 'VIOL_INFAN', 'AG_FORCA', 'AG_ENFOR',
                'AG_OBJETO', 'AG_CORTE', 'AG_QUENTE', 'AG_ENVEN', 'AG_FOGO', 'AG_AMEACA', 'SEX_ESTUPR',
                'SEX_PUDOR', 'SEX_EXPLO', 'SEX_PORNO', 'REL_PAI', 'REL_PAD', 'REL_MAD', 'REL_CONJ', 'REL_EXCON',
                'REL_NAMO', 'REL_EXNAM', 'REL_FILHO', 'REL_DESCO', 'REL_IRMAO', 'REL_CUIDA', 'REL_CONHEC',
                'REL_PATRAO', 'REL_INST', 'REL_MAE', 'REL_POL', 'AUTOR_ALCO', 'ENC_TUTELA',
                'ENC_VARA', 'ENC_ABRIGO', 'ENC_SENTIN', 'ENC_DEAM', 'ENC_DPCA', 'ENC_DELEG', 'ENC_MPU',
                'ENC_MULHER', 'ENC_CREAS', 'ENC_IML', 'REL_TRAB', 'REDE_SAU', 'ASSIST_SOC', 'REDE_EDUCA',
                'ATEND_MULH', 'DIR_HUMAN', 'MPU', 'DELEG_MULH', 'DELEG', 'DEFEN_PUBL', 'ENC_SAUDE', 'SEX_ASSEDI']

col_data_hora = ['DT_ENCERRA', 'DT_OBITO', 'HORA_OCOR', 'DT_OCOR', 'DT_NOTIFIC']

col_outros_tratamentos = ['AUTOR_SEXO', 'NUM_ENVOLV', 'LOCAL_OCOR', 'ID_MN_OCOR', 'ANO_NASC',
                          'SG_UF_OCOR', 'ID_OCUPA_N', 'ID_PAIS', 'ID_MN_RESI', 'SG_UF', 'CS_ESCOL_N', 'CS_RACA',
                          'CS_GESTANT', 'ID_MUNICIP', 'SG_UF_NOT', 'NU_ANO', 'ORIENT_SEX', 'IDENT_GEN', 'VIOL_MOTIV',
                          'CICL_VID', 'SIT_CONJUG', 'ID_UNIDADE']

col_fora_dict = ['CLASSI_FIN', 'EVOLUCAO', 'REL_SEXUAL', 'LESAO_CORP', 'LESAO_NAT', 'LESAO_ESPE']

col_drop = ['TP_NOT']

col_filtragem = ['CS_SEXO', 'NDUPLIC']

listas_tratamentos = ['col_conjunto', 'col_data_hora', 'col_outros_tratamentos', 'col_fora_dict', 'col_drop',
                      'col_filtragem']


In [5]:
len(col_conjunto+col_data_hora+col_outros_tratamentos+col_fora_dict+col_drop+col_filtragem)

100

In [6]:
for coluna in df.columns:
    print(f'{coluna}\n{df[coluna].unique()}\n\n')

TP_NOT
[2]


DT_NOTIFIC
['2009-05-12' '2009-12-01' '2009-01-22' ... '2021-12-18' '2021-12-19'
 '2021-12-20']


NU_ANO
[2009. 2010. 2011. 2012. 2013. 2014. 2015. 2016. 2017. 2018. 2019.   nan
 2020. 2021.]


SG_UF_NOT
[41 29 52 13 26 23 25 42 21 43 50 27 14 22 35 31 12 33 15 53 32 24 51 11
 28 17 16]


ID_MUNICIP
[412550 290270 520870 ... 353990 250880 250153]


ID_UNIDADE
[2753278. 2301687. 2338262. ... 3599426. 5359244. 2364336.]


DT_OCOR
[20090512. 20091201. 20090122. ... 20020824. 19970812. 20071207.]


ANO_NASC
[2004. 1980.   nan 2009. 1988. 1976. 1969. 1942. 1950. 1982. 1983. 1963.
 1967. 1971. 2005. 1993. 2001. 2008. 1975. 2002. 1966. 1917. 1986. 1973.
 1994. 1978. 1992. 1984. 1989. 1991. 1965. 1979. 1995. 1958. 1999. 1981.
 1946. 1970. 1968. 1972. 1964. 1977. 1990. 1987. 1985. 1945. 1998. 1996.
 1960. 1934. 1941. 1974. 2003. 2006. 1940. 1927. 1957. 2007. 1997. 1961.
 1944. 1956. 1962. 1951. 1959. 1933. 1939. 1953. 1937. 1929. 1915. 1943.
 2000. 1925. 1923. 1955. 1948. 1949. 194

## Transformando nulos em nulos

In [7]:
df.replace('', None, inplace=True)

In [8]:
for coluna in df.columns:
    print(f'{coluna}\n{df[coluna].unique()}\n\n')

TP_NOT
[2]


DT_NOTIFIC
['2009-05-12' '2009-12-01' '2009-01-22' ... '2021-12-18' '2021-12-19'
 '2021-12-20']


NU_ANO
[2009. 2010. 2011. 2012. 2013. 2014. 2015. 2016. 2017. 2018. 2019.   nan
 2020. 2021.]


SG_UF_NOT
[41 29 52 13 26 23 25 42 21 43 50 27 14 22 35 31 12 33 15 53 32 24 51 11
 28 17 16]


ID_MUNICIP
[412550 290270 520870 ... 353990 250880 250153]


ID_UNIDADE
[2753278. 2301687. 2338262. ... 3599426. 5359244. 2364336.]


DT_OCOR
[20090512. 20091201. 20090122. ... 20020824. 19970812. 20071207.]


ANO_NASC
[2004. 1980.   nan 2009. 1988. 1976. 1969. 1942. 1950. 1982. 1983. 1963.
 1967. 1971. 2005. 1993. 2001. 2008. 1975. 2002. 1966. 1917. 1986. 1973.
 1994. 1978. 1992. 1984. 1989. 1991. 1965. 1979. 1995. 1958. 1999. 1981.
 1946. 1970. 1968. 1972. 1964. 1977. 1990. 1987. 1985. 1945. 1998. 1996.
 1960. 1934. 1941. 1974. 2003. 2006. 1940. 1927. 1957. 2007. 1997. 1961.
 1944. 1956. 1962. 1951. 1959. 1933. 1939. 1953. 1937. 1929. 1915. 1943.
 2000. 1925. 1923. 1955. 1948. 1949. 194

In [9]:
df.isna().mean()*100

TP_NOT          0.000000
DT_NOTIFIC      0.000000
NU_ANO          0.001411
SG_UF_NOT       0.000000
ID_MUNICIP      0.000000
ID_UNIDADE      0.180020
DT_OCOR         0.817001
ANO_NASC        2.581563
CS_SEXO         0.000000
CS_GESTANT      0.000000
CS_RACA         1.284959
CS_ESCOL_N      5.774937
SG_UF           0.016055
ID_MN_RESI      0.016055
ID_PAIS         0.271765
NDUPLIC       100.000000
ID_OCUPA_N     54.280581
SIT_CONJUG      2.689070
DEF_TRANS       1.873362
SG_UF_OCOR      2.814690
ID_MN_OCOR      3.859348
HORA_OCOR      43.547356
LOCAL_OCOR      1.475036
OUT_VEZES       2.135659
LES_AUTOP       2.662134
VIOL_FISIC      1.908708
VIOL_PSICO      3.632808
VIOL_TORT       4.623301
VIOL_SEXU       4.231268
VIOL_TRAF       4.707460
VIOL_FINAN      4.660470
VIOL_LEGAL      4.720045
VIOL_NEGLI      4.216742
VIOL_INFAN      4.732866
AG_FORCA        3.252831
AG_ENFOR        5.376081
AG_OBJETO       5.398900
AG_CORTE        5.228407
AG_QUENTE       5.474236
AG_ENVEN        5.546162


## Transformando numéricos em numéricos

In [10]:
listas_tratamentos

['col_conjunto',
 'col_data_hora',
 'col_outros_tratamentos',
 'col_fora_dict',
 'col_drop',
 'col_filtragem']

In [11]:
print(len(df.columns))
df[col_conjunto + col_outros_tratamentos + col_fora_dict +
     col_drop + col_filtragem ] =  df[col_conjunto + col_outros_tratamentos +
                                        col_fora_dict + col_drop + col_filtragem
                                        ].apply(pd.to_numeric, errors='coerce')

100


In [12]:
len(df.columns)

100

## Alterando resposta das colunas
- Conjunto de colunas com
  - 1: sim
  - 2: nao
  - 8: não aplicavel
  - 9: ignorado

- Data e hora

- Outros tratamentos

- Drop

### Dropar colunas
listas: 'col_fora_dict', 'col_drop', 'col_filtragem',

In [13]:
df = df.drop(col_fora_dict + col_drop + col_filtragem, axis=1)

In [14]:
len(df.columns)

91

### Conjunto de colunas com mesmo tratamento
lista: col_conjunto




In [15]:
mapeamento = {1.0: 'Sim',
              2.0: 'Não',
              8.0: 'Não aplicável',
              9.0: 'Ignorado'}

for coluna in col_conjunto:
    df[coluna] = df[coluna].map(lambda x: mapeamento.get(x, np.nan))

for coluna in col_conjunto:
    print(f'{coluna}\n{df[coluna].unique()}\n\n')

DEF_TRANS
['Não' 'Ignorado' 'Sim' nan 'Não aplicável']


OUT_VEZES
['Não' 'Ignorado' 'Sim' nan]


LES_AUTOP
['Não' 'Ignorado' nan 'Sim']


VIOL_FISIC
['Sim' 'Não' nan 'Ignorado']


VIOL_PSICO
['Não' 'Sim' 'Ignorado' nan]


VIOL_TORT
['Não' 'Sim' 'Ignorado' nan]


VIOL_SEXU
['Não' 'Sim' 'Ignorado' nan]


VIOL_TRAF
['Não' 'Ignorado' nan 'Sim']


VIOL_FINAN
['Não' 'Ignorado' nan 'Sim']


VIOL_LEGAL
['Não' 'Ignorado' nan 'Sim']


VIOL_NEGLI
['Sim' 'Não' 'Ignorado' nan]


VIOL_INFAN
['Não' 'Ignorado' nan 'Sim']


AG_FORCA
['Sim' 'Não' 'Ignorado' nan]


AG_ENFOR
['Não' 'Ignorado' nan 'Sim']


AG_OBJETO
['Não' 'Ignorado' 'Sim' nan]


AG_CORTE
['Não' 'Sim' 'Ignorado' nan]


AG_QUENTE
['Não' 'Ignorado' 'Sim' nan]


AG_ENVEN
['Não' 'Ignorado' nan 'Sim']


AG_FOGO
['Não' 'Ignorado' 'Sim' nan]


AG_AMEACA
['Não' 'Ignorado' 'Sim' nan]


SEX_ESTUPR
['Não aplicável' 'Sim' nan 'Não' 'Ignorado']


SEX_PUDOR
['Não aplicável' 'Não' 'Sim' nan 'Ignorado']


SEX_EXPLO
['Não aplicável' 'Sim' 'Não' nan 'Ignor

### Data e hora

In [16]:
for coluna in col_data_hora:
    print(f'{coluna}\n{df[coluna].unique()}\n\n')

DT_ENCERRA
[20090512. 20091201. 20090122. ... 20220813. 20220814. 20220821.]


DT_OBITO
[      nan 20090308. 20090409. ... 20140617. 20141225. 20150402.]


HORA_OCOR
[nan '09:00' '22:00' ... '04:48' '00000' '05:36']


DT_OCOR
[20090512. 20091201. 20090122. ... 20020824. 19970812. 20071207.]


DT_NOTIFIC
['2009-05-12' '2009-12-01' '2009-01-22' ... '2021-12-18' '2021-12-19'
 '2021-12-20']




In [17]:
df[['DT_ENCERRA', 'DT_OBITO', 'DT_OCOR']] = df[['DT_ENCERRA', 'DT_OBITO', 'DT_OCOR']].fillna('00010101').astype(int).astype(str)

In [18]:
# Verifique se os valores não atendem ao padrão usando regex e negando a condição
padrao = r'^\d{4}(0[1-9]|1[0-2])(0[1-9]|[12]\d|3[01])$'
valores_nao_corretos = ~df['DT_ENCERRA'].str.match(padrao, na=False)

# Crie um novo DataFrame com os valores que não atendem ao padrão
df_nao_corretos = df[valores_nao_corretos]

# Imprima os resultados, se desejar
print("Valores que não atendem ao padrão:")
print(df_nao_corretos['DT_ENCERRA'].head())

Valores que não atendem ao padrão:
22      10101
476     10101
796     10101
1388    10101
2250    10101
Name: DT_ENCERRA, dtype: object


In [19]:
df.loc[df.DT_ENCERRA == '10101','DT_ENCERRA'] = '00010101'
df.loc[df.DT_OBITO == '10101','DT_OBITO'] = '00010101'
df.loc[df.DT_OCOR == '10101','DT_OCOR'] = '00010101'

In [20]:
df[['DT_ENCERRA', 'DT_OBITO', 'DT_OCOR']] = df[['DT_ENCERRA', 'DT_OBITO',
                                                    'DT_OCOR']].replace('00010101', np.nan)

df['DT_ENCERRA'] = pd.to_datetime(df['DT_ENCERRA'], format='%Y%m%d').dt.strftime('%d/%m/%Y')
df['DT_OBITO'] = pd.to_datetime(df['DT_OBITO'], format='%Y%m%d').dt.strftime('%d/%m/%Y')
df['DT_OCOR'] = pd.to_datetime(df['DT_OCOR'], format='%Y%m%d').dt.strftime('%d/%m/%Y')

In [21]:
df['DT_NOTIFIC'] = pd.to_datetime(df['DT_NOTIFIC'], format='%Y-%m-%d').dt.strftime('%d/%m/%Y')

In [22]:
df.loc[df.HORA_OCOR == '00000'] = np.nan
df['HORA_OCOR'] = pd.to_datetime(df['HORA_OCOR'], format='%H:%M').dt.strftime('%H:%M')

### Outros tratamentos
Aqui tem que tratar coluna por coluna

lista: col_outros_tratamentos

#### AUTOR_SEXO

In [23]:
df.AUTOR_SEXO.unique()

array([ 2.,  1.,  9., nan,  3.])

In [24]:
mapeamento = {1.0: 'Masculino',
              2.0: 'Feminino',
              8.0: 'Ambos',
              9.0: 'Ignorado'}

coluna = 'AUTOR_SEXO'

# Substituir valores diferentes pelos que estão no mapeamento e o restante por NaN
df[coluna] = df[coluna].map(lambda x: mapeamento.get(x, np.nan))

df[coluna].unique()

array(['Feminino', 'Masculino', 'Ignorado', nan], dtype=object)

#### NUM_ENVOLV


In [25]:
df.NUM_ENVOLV.unique()

array([ 1.,  9.,  2., nan,  3.])

In [26]:
mapeamento = {1.0: 'Um',
              2.0: 'Dois ou mais',
              9.0: 'Ignorado'}

coluna = 'NUM_ENVOLV'

# Substituir valores diferentes pelos que estão no mapeamento e o restante por NaN
df[coluna] = df[coluna].map(lambda x: mapeamento.get(x, np.nan))

df[coluna].unique()

array(['Um', 'Ignorado', 'Dois ou mais', nan], dtype=object)

#### LOCAL_OCOR

In [27]:
df.LOCAL_OCOR.unique()

array([ 1.,  7., 99.,  9.,  6., nan,  3.,  2.,  5.,  4.,  8.])

In [28]:
mapeamento = {1.0: 'Residência',
              2.0: 'Habitação_coletiva',
              3.0: 'Escola',
              4.0: 'Local_prática_esportiva',
              5.0: 'Bar_ou_similar',
              6.0: 'Via_publica',
              7.0: 'Comércio_serviços',
              8.0: 'Industrias_construção',
              9.0: 'Outros',
              99.0: 'Ignorado'}

coluna = 'LOCAL_OCOR'

# Substituir valores diferentes pelos que estão no mapeamento e o restante por NaN
df[coluna] = df[coluna].map(lambda x: mapeamento.get(x, np.nan))

df[coluna].unique()

array(['Residência', 'Comércio_serviços', 'Ignorado', 'Outros',
       'Via_publica', nan, 'Escola', 'Habitação_coletiva',
       'Bar_ou_similar', 'Local_prática_esportiva',
       'Industrias_construção'], dtype=object)

#### ID_MN_OCOR
Na tabela são 6 digitos, mas na tabela vinda do IBGE são 7, então não tem correspondencia

In [29]:
df_municipio = pd.read_excel('RELATORIO_DTB_BRASIL_MUNICIPIO.xls', skiprows=6, header=0)

WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
*** No CODEPAGE record, no encoding_override: will use 'iso-8859-1'


In [30]:
df_municipio.head(20)

UF   Nome_UF  Região Geográfica Intermediária  \
0   11  Rondônia                             1102   
1   11  Rondônia                             1102   
2   11  Rondônia                             1101   
3   11  Rondônia                             1102   
4   11  Rondônia                             1101   
5   11  Rondônia                             1101   
6   11  Rondônia                             1102   
7   11  Rondônia                             1101   
8   11  Rondônia                             1102   
9   11  Rondônia                             1101   
10  11  Rondônia                             1101   
11  11  Rondônia                             1102   
12  11  Rondônia                             1102   
13  11  Rondônia                             1102   
14  11  Rondônia                             1102   
15  11  Rondônia                             1102   
16  11  Rondônia                             1102   
17  11  Rondônia                             1101   
18  11  Rondônia                             1102   
19  11  Rondônia                             1101   

   Nome Região Geográfica Intermediária  Região Geográfica Imediata  \
0                             Ji-Paraná                      110005   
1                             Ji-Paraná                      110005   
2                           Porto Velho                      110002   
3                             Ji-Paraná                      110004   
4                           Porto Velho                      110002   
5                           Porto Velho                      110002   
6                             Ji-Paraná                      110006   
7                           Porto Velho                      110002   
8                             Ji-Paraná                      110005   
9                           Porto Velho                      110002   
10                          Porto Velho                      110001   
11                            Ji-Paraná                      110005   
12                            Ji-Paraná                      110006   
13                            Ji-Paraná                      110006   
14                            Ji-Paraná                      110006   
15                            Ji-Paraná                      110006   
16                            Ji-Paraná                      110004   
17                          Porto Velho                      110002   
18                            Ji-Paraná                      110005   
19                          Porto Velho                      110003   

   Nome Região Geográfica Imediata  Mesorregião Geográfica   Nome_Mesorregião  \
0                           Cacoal                       2  Leste Rondoniense   
1                           Cacoal                       2  Leste Rondoniense   
2                        Ariquemes                       2  Leste Rondoniense   
3                        Ji-Paraná                       2  Leste Rondoniense   
4                        Ariquemes                       2  Leste Rondoniense   
5                        Ariquemes                       1    Madeira-Guaporé   
6                          Vilhena                       2  Leste Rondoniense   
7                        Ariquemes                       2  Leste Rondoniense   
8                           Cacoal                       2  Leste Rondoniense   
9                        Ariquemes                       1    Madeira-Guaporé   
10                     Porto Velho                       1    Madeira-Guaporé   
11                          Cacoal                       2  Leste Rondoniense   
12                         Vilhena                       2  Leste Rondoniense   
13                         Vilhena                       2  Leste Rondoniense   
14                         Vilhena                       2  Leste Rondoniense   
15                         Vilhena                       2  Leste Rondoniense   
16                   

In [31]:
df.ID_MN_OCOR.unique()

array([412550., 292160., 520000., ..., 350470., 241080., 353700.])

#### ID_MN_RESI

In [32]:
df.ID_MN_RESI.unique()

array([412550., 292160., 522045., ..., 240390., 520120., 330090.])

#### ID_MUNICIP
Mesmo caso do anterior

In [33]:
df.ID_MUNICIP.unique()

array([412550., 290270., 520870., ..., 353990., 250880., 250153.])

#### SG_UF_OCOR



In [34]:
df_uf = df_municipio.groupby('Nome_UF')['UF'].min().reset_index()
df_uf.set_index("UF", inplace=True)

In [35]:
df_uf.head()

Nome_UF
UF          
12      Acre
27   Alagoas
16     Amapá
13  Amazonas
29     Bahia

In [36]:
df.SG_UF_OCOR.unique()

array([41., 29., 52., 13., 26., nan, 23., 25., 42., 21., 43., 32., 50.,
       35., 14., 22., 33., 12., 15., 11., 53., 31., 17., 24., 51., 28.,
       27., 16.])

In [37]:
mapeamento = df_uf["Nome_UF"].to_dict()

coluna = 'SG_UF_OCOR'

# Substituir valores diferentes pelos que estão no mapeamento e o restante por NaN
df[coluna] = df[coluna].map(lambda x: mapeamento.get(x, np.nan))

df[coluna].unique()

array(['Paraná', 'Bahia', 'Goiás', 'Amazonas', 'Pernambuco', nan, 'Ceará',
       'Paraíba', 'Santa Catarina', 'Maranhão', 'Rio Grande do Sul',
       'Espírito Santo', 'Mato Grosso do Sul', 'São Paulo', 'Roraima',
       'Piauí', 'Rio de Janeiro', 'Acre', 'Pará', 'Rondônia',
       'Distrito Federal', 'Minas Gerais', 'Tocantins',
       'Rio Grande do Norte', 'Mato Grosso', 'Sergipe', 'Alagoas',
       'Amapá'], dtype=object)

#### SG_UF
Não sei se é igual ou não a coluna tratada acima

In [38]:
df.SG_UF.unique()

array([41., 29., 52., 13., 26., 23., 25., 42., 35., 21., 43., 50., 27.,
       14., 22., nan, 31., 12., 33., 15., 11., 53., 32., 24., 51., 28.,
       17., 16.])

In [39]:
mapeamento = df_uf["Nome_UF"].to_dict()

coluna = 'SG_UF'

# Substituir valores diferentes pelos que estão no mapeamento e o restante por NaN
df[coluna] = df[coluna].map(lambda x: mapeamento.get(x, np.nan))

df[coluna].unique()

array(['Paraná', 'Bahia', 'Goiás', 'Amazonas', 'Pernambuco', 'Ceará',
       'Paraíba', 'Santa Catarina', 'São Paulo', 'Maranhão',
       'Rio Grande do Sul', 'Mato Grosso do Sul', 'Alagoas', 'Roraima',
       'Piauí', nan, 'Minas Gerais', 'Acre', 'Rio de Janeiro', 'Pará',
       'Rondônia', 'Distrito Federal', 'Espírito Santo',
       'Rio Grande do Norte', 'Mato Grosso', 'Sergipe', 'Tocantins',
       'Amapá'], dtype=object)

#### SG_UF_NOT
Mesmo caso, nao sei se é igual

In [40]:
df.SG_UF_NOT.unique()

array([41., 29., 52., 13., 26., 23., 25., 42., 21., 43., 50., 27., 14.,
       22., 35., 31., 12., 33., 15., 53., 32., 24., 51., 11., 28., 17.,
       16., nan])

In [41]:
mapeamento = df_uf["Nome_UF"].to_dict()

coluna = 'SG_UF_NOT'

# Substituir valores diferentes pelos que estão no mapeamento e o restante por NaN
df[coluna] = df[coluna].map(lambda x: mapeamento.get(x, np.nan))

df[coluna].unique()

array(['Paraná', 'Bahia', 'Goiás', 'Amazonas', 'Pernambuco', 'Ceará',
       'Paraíba', 'Santa Catarina', 'Maranhão', 'Rio Grande do Sul',
       'Mato Grosso do Sul', 'Alagoas', 'Roraima', 'Piauí', 'São Paulo',
       'Minas Gerais', 'Acre', 'Rio de Janeiro', 'Pará',
       'Distrito Federal', 'Espírito Santo', 'Rio Grande do Norte',
       'Mato Grosso', 'Rondônia', 'Sergipe', 'Tocantins', 'Amapá', nan],
      dtype=object)

#### ID_OCUPA_N
Não informa onde conseguir o de para

In [42]:
df_cbo = pd.read_csv('CBO2002 - Ocupacao.csv', encoding='latin-1', sep=';')

In [43]:
df_cbo.head()

CODIGO                          TITULO
0   10105  Oficial general da aeronáutica
1   10110     Oficial general do exército
2   10115      Oficial general da marinha
3   10205          Oficial da aeronáutica
4   10210             Oficial do exército

In [44]:
df.ID_OCUPA_N.unique()

array([    nan, 524205., 999991., ..., 214745., 762125., 722105.])

In [45]:
df_cbo.set_index("CODIGO", inplace=True)
mapeamento = df_cbo["TITULO"].to_dict()

coluna = 'ID_OCUPA_N'

# Substituir valores diferentes pelos que estão no mapeamento e o restante por NaN
df[coluna] = df[coluna].map(lambda x: mapeamento.get(x, np.nan))

df[coluna].unique()

array([nan, 'Feirante', 'Caseiro (agricultura)', ...,
       'Tecnólogo em petróleo e gás', 'Rachador de couros e peles',
       'Forjador'], dtype=object)

#### ID_PAIS
Não informa onde conseguir o de para. Dei uma olhada no M49 Code list que é o que fala quando pesquiso no IBGE, mas não fez sentido, visto que nenhum dos casos que tem no unique seria Brasil. Como todos tem algum municipio, creio ser tudo Brasil na verdade.

In [46]:
df.ID_PAIS.unique()

array([  1.,   9.,  41.,  nan,  32.,  19.,  12.,  68.,  13.,  43.,  15.,
         7.,  14.,  45.,  18.,  92.,  54.,  38.,  46.,  37.,  16., 199.,
       126., 138.,  65.,  71., 137., 192., 196., 153., 151.,  96.])

#### CS_ESCOL_N

In [47]:
df.CS_ESCOL_N.unique()

array([10.,  6.,  9.,  4.,  1.,  3., nan,  8.,  2.,  5.,  7.,  0.])

In [48]:
mapeamento = {0.0: 'Analfabeto',
              1.0: 'Fundamental I incompleto',
              2.0: 'Fundamental I completo',
              3.0: 'Fundamental II incompleto',
              4.0: 'Fundamental II completo',
              5.0: 'Ensino médio incompleto',
              6.0: 'Ensino médio completo',
              7.0: 'Educação superior incompleta',
              8.0: 'Educação superior completa',
              9.0: 'Ignorado',
              10.0: 'Não aplicável'}

coluna = 'CS_ESCOL_N'

# Substituir valores diferentes pelos que estão no mapeamento e o restante por NaN
df[coluna] = df[coluna].map(lambda x: mapeamento.get(x, np.nan))

df[coluna].unique()

array(['Não aplicável', 'Ensino médio completo', 'Ignorado',
       'Fundamental II completo', 'Fundamental I incompleto',
       'Fundamental II incompleto', nan, 'Educação superior completa',
       'Fundamental I completo', 'Ensino médio incompleto',
       'Educação superior incompleta', 'Analfabeto'], dtype=object)

#### CS_RACA

In [49]:
df.CS_RACA.unique()

array([ 1.,  2.,  9.,  4.,  5., nan,  3.])

In [50]:
mapeamento = {1.0: 'Branca',
              2.0: 'Preta',
              3.0: 'Amarela',
              4.0: 'Parda',
              5.0: 'Indigena'}

coluna = 'CS_RACA'

# Substituir valores diferentes pelos que estão no mapeamento e o restante por NaN
df[coluna] = df[coluna].map(lambda x: mapeamento.get(x, np.nan))

df[coluna].unique()

array(['Branca', 'Preta', nan, 'Parda', 'Indigena', 'Amarela'],
      dtype=object)

#### CS_GESTANT

In [51]:
df.CS_GESTANT.unique()

array([ 6.,  5.,  9.,  4.,  3.,  1.,  2., nan,  8.])

In [52]:
mapeamento = {1.0: '1º Trimestre',
              2.0: '2º Trimestre',
              3.0: '3º Trimestre',
              4.0: 'Idade gestacional ignorada',
              5.0: 'Não',
              6.0: 'Não se aplica',
              9.0: 'Ignorado' }

coluna = 'CS_GESTANT'

# Substituir valores diferentes pelos que estão no mapeamento e o restante por NaN
df[coluna] = df[coluna].map(lambda x: mapeamento.get(x, np.nan))

df[coluna].unique()

array(['Não se aplica', 'Não', 'Ignorado', 'Idade gestacional ignorada',
       '3º Trimestre', '1º Trimestre', '2º Trimestre', nan], dtype=object)

#### NU_ANO e ANO_NASC


In [53]:
df.NU_ANO.unique()

array([2009., 2010., 2011., 2012., 2013.,   nan, 2014., 2015., 2016.,
       2017., 2018., 2019., 2020., 2021.])

In [54]:
df.ANO_NASC.unique()

array([2004., 1980.,   nan, 2009., 1988., 1976., 1969., 1942., 1950.,
       1982., 1983., 1963., 1967., 1971., 2005., 1993., 2001., 2008.,
       1975., 2002., 1966., 1917., 1986., 1973., 1994., 1978., 1992.,
       1984., 1989., 1991., 1965., 1979., 1995., 1958., 1999., 1981.,
       1946., 1970., 1968., 1972., 1964., 1977., 1990., 1987., 1985.,
       1945., 1998., 1996., 1960., 1934., 1941., 1974., 2003., 2006.,
       1940., 1927., 1957., 2007., 1997., 1961., 1944., 1956., 1962.,
       1951., 1959., 1933., 1939., 1953., 1937., 1929., 1915., 1943.,
       2000., 1925., 1923., 1955., 1948., 1949., 1947., 1952., 1935.,
       1936., 1931., 1938., 1912., 1930., 1954., 1916., 1932., 1906.,
       1922., 1921., 1914., 1926., 1924., 1910., 1928., 1919., 1907.,
       1920., 1908., 1918., 1911., 1913., 2010., 1901., 2011., 1909.,
       1904., 1900., 1905., 2012., 1902., 2013., 1903., 2014., 2015.,
       2016., 2017., 2018., 2019., 2020., 2021.])

In [55]:
df['IDADE'] = df['NU_ANO'] - df['ANO_NASC']

In [56]:
df.IDADE.unique()

array([  5.,  29.,  nan,   0.,  21.,  33.,  40.,  67.,  59.,  27.,  26.,
        46.,  42.,  38.,   4.,  16.,   8.,   1.,  34.,   7.,  43.,  92.,
        23.,  36.,  15.,  31.,  17.,  25.,  20.,  18.,  44.,  30.,  14.,
        51.,  10.,  28.,  63.,  39.,  41.,  37.,  45.,  32.,  19.,  22.,
        24.,  64.,  11.,  13.,  49.,  75.,  68.,  35.,   6.,   3.,  69.,
        82.,  52.,   2.,  12.,  48.,  65.,  53.,  47.,  58.,  50.,  76.,
        70.,  56.,  72.,  80.,  94.,  66.,   9.,  84.,  86.,  54.,  61.,
        60.,  62.,  57.,  74.,  73.,  78.,  71.,  97.,  79.,  55.,  93.,
        77., 103.,  87.,  88.,  95.,  83.,  85.,  99.,  81.,  90., 102.,
        89., 101.,  91.,  98.,  96., 100., 109., 105., 107., 111., 106.,
       110., 104., 108., 112., 113., 114., 115., 116., 117., 118., 119.,
       121.])

#### ORIENT_SEX

In [57]:
df.ORIENT_SEX.unique()

array([nan,  9.,  1.,  8.,  2.,  3.])

In [58]:
mapeamento = {1.0: 'Heterossexual',
              2.0: 'Homossexual',
              3.0: 'Bissexual',
              8.0: 'Não se aplica',
              9.0: 'Ignorado'}

coluna = 'ORIENT_SEX'

# Substituir valores diferentes pelos que estão no mapeamento e o restante por NaN
df[coluna] = df[coluna].map(lambda x: mapeamento.get(x, np.nan))

df[coluna].unique()

array([nan, 'Ignorado', 'Heterossexual', 'Não se aplica', 'Homossexual',
       'Bissexual'], dtype=object)

#### IDENT_GEN

In [59]:
df.IDENT_GEN.unique()

array([nan,  9.,  8.,  2.,  3.,  1.])

In [60]:
mapeamento = {1.0: 'Travesti',
              2.0: 'Transexual Mulher',
              3.0: 'Transexual Homem',
              4.0: 'Não se aplica',
              5.0: 'Ignorado'}

coluna = 'IDENT_GEN'

# Substituir valores diferentes pelos que estão no mapeamento e o restante por NaN
df[coluna] = df[coluna].map(lambda x: mapeamento.get(x, np.nan))

df[coluna].unique()

array([nan, 'Transexual Mulher', 'Transexual Homem', 'Travesti'],
      dtype=object)

#### VIOL_MOTIV

In [61]:
df.VIOL_MOTIV.unique()

array([nan,  9., 88., 99.,  6.,  7.,  8.,  1.,  2.,  4.,  3.,  5.])

In [62]:
mapeamento = {1.0: 'Sexismo',
              2.0: 'Homofobia/Lesbofobia/Bifobia/Transfobia',
              3.0: 'Racismo',
              4.0: 'Intolerância religiosa',
              5.0: 'Xenofobia',
              6.0: 'Conflito geracional',
              7.0: 'Situação de rua',
              8.0: 'Deficiência',
              9.0: 'Outros',
              88.0: 'Não se aplica',
              99.0: 'Ignorado'}

coluna = 'VIOL_MOTIV'

# Substituir valores diferentes pelos que estão no mapeamento e o restante por NaN
df[coluna] = df[coluna].map(lambda x: mapeamento.get(x, np.nan))

df[coluna].unique()

array([nan, 'Outros', 'Não se aplica', 'Ignorado', 'Conflito geracional',
       'Situação de rua', 'Deficiência', 'Sexismo',
       'Homofobia/Lesbofobia/Bifobia/Transfobia',
       'Intolerância religiosa', 'Racismo', 'Xenofobia'], dtype=object)

#### CICL_VID

In [63]:
df.CICL_VID.unique()

array([nan,  9.,  4.,  3.,  2.,  1.,  5.])

In [64]:
mapeamento = {1.0: 'Criança',
              2.0: 'Adolescente',
              3.0: 'Jovem',
              4.0: 'Pessoa adulta',
              5.0: 'Pessoa idosa',
              9.0: 'Ignorado'}

coluna = 'CICL_VID'

# Substituir valores diferentes pelos que estão no mapeamento e o restante por NaN
df[coluna] = df[coluna].map(lambda x: mapeamento.get(x, np.nan))

df[coluna].unique()

array([nan, 'Ignorado', 'Pessoa adulta', 'Jovem', 'Adolescente',
       'Criança', 'Pessoa idosa'], dtype=object)

#### SIT_CONJUG

In [65]:
df.SIT_CONJUG.unique()

array([ 8.,  2.,  9.,  1., nan,  4.,  3.])

In [66]:
mapeamento = {1.0: 'Solteiro',
              2.0: 'Casado/ União consensual',
              3.0: 'Viúvo',
              4.0: 'Separado',
              8.0: 'Não aplicável',
              9.0: 'Ignorado'}

coluna = 'SIT_CONJUG'

# Substituir valores diferentes pelos que estão no mapeamento e o restante por NaN
df[coluna] = df[coluna].map(lambda x: mapeamento.get(x, np.nan))

df[coluna].unique()

array(['Não aplicável', 'Casado/ União consensual', 'Ignorado',
       'Solteiro', nan, 'Separado', 'Viúvo'], dtype=object)

#### ID_UNIDADE
O site não está funcionando para extração: https://cnes.datasus.gov.br/pages/downloads/arquivosBaseDados.jsp

In [67]:
df.ID_UNIDADE.unique()

array([2753278., 2301687., 2338262., ..., 3599426., 5359244., 2364336.])

In [68]:
df.shape

(1700365, 92)

In [69]:
df.head()

DT_NOTIFIC  NU_ANO   SG_UF_NOT  ID_MUNICIP  ID_UNIDADE     DT_OCOR  \
0  12/05/2009  2009.0      Paraná    412550.0   2753278.0  12/05/2009   
1  01/12/2009  2009.0       Bahia    290270.0   2301687.0  01/12/2009   
2  22/01/2009  2009.0       Goiás    520870.0   2338262.0  22/01/2009   
3  01/03/2009  2009.0    Amazonas    130356.0   2708930.0  01/03/2009   
4  30/06/2009  2009.0  Pernambuco    260290.0   5581923.0  30/06/2009   

   ANO_NASC     CS_GESTANT CS_RACA               CS_ESCOL_N  ... ASSIST_SOC  \
0    2004.0  Não se aplica  Branca            Não aplicável  ...        NaN   
1    1980.0            Não   Preta    Ensino médio completo  ...        NaN   
2    1980.0       Ignorado     NaN                 Ignorado  ...        NaN   
3       NaN            Não   Parda  Fundamental II completo  ...        NaN   
4    2009.0  Não se aplica   Parda            Não aplicável  ...        NaN   

   REDE_EDUCA  ATEND_MULH DIR_HUMAN  MPU DELEG_MULH DELEG  DEFEN_PUBL  \
0         NaN         NaN       NaN  NaN        NaN   NaN         NaN   
1         NaN         NaN       NaN  NaN        NaN   NaN         NaN   
2         NaN         NaN       NaN  NaN        NaN   NaN         NaN   
3         NaN         NaN       NaN  NaN        NaN   NaN         NaN   
4         NaN         NaN       NaN  NaN        NaN   NaN         NaN   

   DT_ENCERRA IDADE  
0  12/05/2009   5.0  
1  01/12/2009  29.0  
2  22/01/2009  29.0  
3  01/03/2009   NaN  
4  16/07/2009   0.0  

[5 rows x 92 columns]

In [70]:
df.isnull().mean().round()*100

DT_NOTIFIC      0.0
NU_ANO          0.0
SG_UF_NOT       0.0
ID_MUNICIP      0.0
ID_UNIDADE      0.0
DT_OCOR         0.0
ANO_NASC        0.0
CS_GESTANT      0.0
CS_RACA         0.0
CS_ESCOL_N      0.0
SG_UF           0.0
ID_MN_RESI      0.0
ID_PAIS         0.0
ID_OCUPA_N    100.0
SIT_CONJUG      0.0
DEF_TRANS       0.0
SG_UF_OCOR      0.0
ID_MN_OCOR      0.0
HORA_OCOR       0.0
LOCAL_OCOR      0.0
OUT_VEZES       0.0
LES_AUTOP       0.0
VIOL_FISIC      0.0
VIOL_PSICO      0.0
VIOL_TORT       0.0
VIOL_SEXU       0.0
VIOL_TRAF       0.0
VIOL_FINAN      0.0
VIOL_LEGAL      0.0
VIOL_NEGLI      0.0
VIOL_INFAN      0.0
AG_FORCA        0.0
AG_ENFOR        0.0
AG_OBJETO       0.0
AG_CORTE        0.0
AG_QUENTE       0.0
AG_ENVEN        0.0
AG_FOGO         0.0
AG_AMEACA       0.0
SEX_ASSEDI      0.0
SEX_ESTUPR      0.0
SEX_PUDOR     100.0
SEX_EXPLO       0.0
SEX_PORNO       0.0
NUM_ENVOLV      0.0
REL_PAI         0.0
REL_PAD         0.0
REL_MAD         0.0
REL_CONJ        0.0
REL_EXCON       0.0


In [71]:
df.to_csv('drive/MyDrive/violencia_2009_2021_tratado.csv', index = False)